### PR TITLE
Update contributeactiondev.rst

### PR DESCRIPTION
**Pull request by parteekcoder**
Hi @pradeeban ,

I updated all the parameters required to work with this current architecture. Now could please go through the dev docs of contribute action and add the tokens where ever explained in the docs. I will be happy to hear if any step is unclear and confusing.

### CODE REVIEW

**Comment by parteekcoder** [comment]
Once this is done and all PR got merged, please tell me so that I can test  this implementation with our new configuration


Thanks for considering this PR

**Comment by pradeeban** [comment]
This is great.

At some point, Mark and I will need to decide how to move the content around. (Like, some of these developer-facing content should not be on the forefront. That will confuse the users as they do not have the capability or reason to configure these, unless they are replicating the repository).

But that is a topic for a later day.

Merged.

**Comment by parteekcoder** [comment]
> Once this is done and all PR got merged, please tell me so that I can test this implementation with our new configuration
> 
> Thanks for considering this PR

I didn't get what you are talking about, but yeah we can discuss this in the next meet

**Comment by pradeeban** [comment]
How to configure the Contribute-Action itself, is a developer-facing documentation. We need a separation of user docs vs. dev docs in a global scale. But that is something we need to discuss in leisure. (Probably Mark and I need to figure that out first).

It was more of a comment for my future reference than one directed at you. :)

**Pull request merged**
